version: "3"
services:
    client:
        build: ./client
        environment:
            REACT_APP_PORT: ${REACT_APP_PORT}
        expose:
            - ${REACT_APP_PORT}
        ports:
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes:
            - ./client/src:/srv/app/fr-shohin-admin-client/src
            - ./client/public:/srv/app/fr-shohin-admin-client/public
        links:
            - server
        command: npm run start
    server:
        build: ./server
        expose:
            - ${APP_SERVER_PORT}
        environment:
            API_HOST: ${API_HOST}
            APP_SERVER_PORT: ${APP_SERVER_PORT}
        ports:
            - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes:
            - ./server:/srv/app/fr-shohin-admin-server
        command: npm run dev